export const FACTION_TALENTS = {
  IRON: {
    id: "IRON",
    name: "鋼鐵要塞",
    desc: "防禦力 (DEF) +4，格擋率 +15%",
    effect: (u) => {
      u.def += 4;
      u.blk += 15;
    },
  },
  WIND: {
    id: "WIND",
    name: "疾風之刃",
    desc: "行動冷卻 (CD) 加快 200ms，閃避率 +15%",
    effect: (u) => {
      u.cd = Math.max(200, u.cd - 200);
      u.eva += 15;
    },
  },
  BLOOD: {
    id: "BLOOD",
    name: "嗜血戰歌",
    desc: "攻擊力 (ATK) +6，最大血量 +20",
    effect: (u) => {
      u.atk += 6;
      u.maxHp += 20;
      u.hp += 20;
    },
  },
};

export const UNIT_BLUEPRINTS = {
  // === 🎯 初始基礎兵種（還原為幾何圖形 Key，修復 shape 報錯） ===
  CIRCLE: {
    shape: "circle",
    label: "坦克",
    maxHp: 1200,
    def: 6,
    atk: 30,
    range: 1,
    cd: 1200,
    eva: 0,
    blk: 15,
    canPromote: true,
    price: 15,
  },
  SQUARE: {
    shape: "square",
    label: "戰士",
    maxHp: 600,
    def: 2,
    atk: 55,
    range: 1,
    cd: 800,
    eva: 5,
    blk: 5,
    canPromote: true,
    price: 15,
  },
  TRI_UP: {
    shape: "triangle-up",
    label: "弓箭手",
    maxHp: 400,
    def: 0,
    atk: 45,
    range: 4,
    cd: 700,
    eva: 10,
    blk: 0,
    canPromote: true,
    price: 15,
  },
  TRI_DOWN: {
    shape: "triangle-down",
    label: "法師",
    maxHp: 450,
    def: 1,
    atk: 60,
    range: 3,
    cd: 1000,
    eva: 3,
    blk: 0,
    canPromote: true,
    price: 15,
  },
  DIAMOND: {
    shape: "diamond",
    label: "刺客",
    maxHp: 350,
    def: 0,
    atk: 70,
    range: 1,
    cd: 500,
    eva: 20,
    blk: 0,
    canPromote: true,
    price: 15,
  },
  CROSS: {
    shape: "cross",
    label: "牧師",
    maxHp: 400,
    def: 1,
    atk: 20,
    range: 2,
    cd: 1000,
    eva: 5,
    blk: 0,
    canPromote: true,
    price: 15,
  },

  // === 🎯 Plus 階級（同步改回幾何圖形加 _PLUS，確保合成邏輯不中斷） ===
  CIRCLE_PLUS: {
    shape: "circle",
    label: "坦克+",
    maxHp: 2200,
    def: 12,
    atk: 55,
    range: 1,
    cd: 1200,
    eva: 0,
    blk: 25,
    canPromote: true,
    isPlus: true,
    price: 35,
  },
  SQUARE_PLUS: {
    shape: "square",
    label: "戰士+",
    maxHp: 1100,
    def: 4,
    atk: 100,
    range: 1,
    cd: 800,
    eva: 8,
    blk: 8,
    canPromote: true,
    isPlus: true,
    price: 35,
  },
  TRI_UP_PLUS: {
    shape: "triangle-up",
    label: "弓箭手+",
    maxHp: 750,
    def: 1,
    atk: 85,
    range: 4,
    cd: 700,
    eva: 15,
    blk: 0,
    canPromote: true,
    isPlus: true,
    price: 35,
  },
  TRI_DOWN_PLUS: {
    shape: "triangle-down",
    label: "法師+",
    maxHp: 800,
    def: 2,
    atk: 110,
    range: 3,
    cd: 1000,
    eva: 5,
    blk: 0,
    canPromote: true,
    isPlus: true,
    price: 35,
  },
  DIAMOND_PLUS: {
    shape: "diamond",
    label: "刺客+",
    maxHp: 650,
    def: 1,
    atk: 130,
    range: 1,
    cd: 500,
    eva: 30,
    blk: 0,
    canPromote: true,
    isPlus: true,
    price: 35,
  },
  CROSS_PLUS: {
    shape: "cross",
    label: "牧師+",
    maxHp: 750,
    def: 2,
    atk: 40,
    range: 3,
    cd: 1000,
    eva: 8,
    blk: 0,
    canPromote: true,
    isPlus: true,
    price: 35,
  },

  // --- 🏆 進階轉職究極體 (Advanced Branch) ---
  BERSERKER: {
    shape: "triangle-up",
    label: "狂戰士",
    maxHp: 1600,
    def: 3,
    atk: 160,
    range: 1,
    cd: 600,
    eva: 10,
    blk: 5,
    canPromote: false,
    isAdvanced: true,
    price: 65,
  },
  BLADEMASTER: {
    shape: "triangle-up",
    label: "大劍師",
    maxHp: 1800,
    def: 5,
    atk: 140,
    range: 1,
    cd: 900,
    eva: 15,
    blk: 10,
    canPromote: false,
    isAdvanced: true,
    price: 65,
  },
  GUARDIAN: {
    shape: "square",
    label: "守護者",
    maxHp: 3800,
    def: 20,
    atk: 80,
    range: 1,
    cd: 1000,
    eva: 0,
    blk: 35,
    canPromote: false,
    isAdvanced: true,
    price: 65,
  },
  CRUSADER: {
    shape: "square",
    label: "黑暗十字軍",
    maxHp: 3200,
    def: 15,
    atk: 110,
    range: 1,
    cd: 1100,
    eva: 5,
    blk: 30,
    canPromote: false,
    isAdvanced: true,
    price: 65,
  },
  MAGIC_ARCHER: {
    shape: "triangle-down",
    label: "魔弓手",
    maxHp: 1200,
    def: 2,
    atk: 130,
    range: 5,
    cd: 600,
    eva: 20,
    blk: 0,
    canPromote: false,
    isAdvanced: true,
    price: 65,
  },
  RANGER: {
    shape: "triangle-down",
    label: "遊俠",
    maxHp: 1100,
    def: 3,
    atk: 150,
    range: 4,
    cd: 500,
    eva: 25,
    blk: 0,
    canPromote: false,
    isAdvanced: true,
    price: 65,
  },
  WARLOCK: {
    shape: "circle",
    label: "術士",
    maxHp: 1300,
    def: 4,
    atk: 160,
    range: 3,
    cd: 1200,
    eva: 10,
    blk: 0,
    canPromote: false,
    isAdvanced: true,
    price: 65,
  },
  ELEMENTALIST: {
    shape: "circle",
    label: "元素使",
    maxHp: 1400,
    def: 5,
    atk: 180,
    range: 4,
    cd: 1400,
    eva: 8,
    blk: 0,
    canPromote: false,
    isAdvanced: true,
    price: 65,
  },
  TRAPMASTER: {
    shape: "diamond",
    label: "陷阱大師",
    maxHp: 1100,
    def: 2,
    atk: 140,
    range: 3,
    cd: 700,
    eva: 25,
    blk: 0,
    canPromote: false,
    isAdvanced: true,
    price: 65,
  },
  UNDERTAKER: {
    shape: "diamond",
    label: "送葬者",
    maxHp: 1400,
    def: 4,
    atk: 190,
    range: 1,
    cd: 500,
    eva: 35,
    blk: 0,
    canPromote: false,
    isAdvanced: true,
    price: 65,
  },
  SAGE: {
    shape: "cross",
    label: "大賢者",
    maxHp: 1200,
    def: 6,
    atk: 50,
    range: 3,
    cd: 900,
    eva: 12,
    blk: 0,
    canPromote: false,
    isAdvanced: true,
    price: 65,
  },
  BLOOD_MAGE: {
    shape: "cross",
    label: "血法師",
    maxHp: 1600,
    def: 4,
    atk: 110,
    range: 2,
    cd: 800,
    eva: 15,
    blk: 0,
    canPromote: false,
    isAdvanced: true,
    price: 65,
  },

  // --- 👑 特殊獨立傳奇職業 ---
  DRAGON_KNIGHT: {
    shape: "diamond",
    label: "龍騎士",
    maxHp: 2500,
    def: 12,
    atk: 150,
    range: 1,
    cd: 1000,
    eva: 10,
    blk: 20,
    canPromote: false,
    isLegendary: true,
    price: 70,
  },
  NINJA: {
    shape: "cross",
    label: "忍者",
    maxHp: 900,
    def: 2,
    atk: 120,
    range: 1,
    cd: 400,
    eva: 45,
    blk: 0,
    canPromote: false,
    isLegendary: true,
    price: 55,
  },
  RONIN: {
    shape: "square",
    label: "浪人",
    maxHp: 1500,
    def: 5,
    atk: 180,
    range: 1,
    cd: 700,
    eva: 30,
    blk: 10,
    canPromote: false,
    isLegendary: true,
    price: 65,
  },
  TEMPLAR: {
    shape: "cross",
    label: "聖堂武士",
    maxHp: 2800,
    def: 18,
    atk: 100,
    range: 1,
    cd: 900,
    eva: 5,
    blk: 25,
    canPromote: false,
    isLegendary: true,
    price: 60,
  },
  MECHANIZED: {
    shape: "square",
    label: "機兵",
    maxHp: 2000,
    def: 10,
    atk: 90,
    range: 2,
    cd: 1500,
    eva: 0,
    blk: 15,
    canPromote: false,
    isLegendary: true,
    price: 60,
  },
};

// === 👹 敵方專屬怪物藍圖 (與玩家招募完全隔離，非鏡像設計) ===
export const ENEMY_BLUEPRINTS = {
  GOBLIN: {
    enemyType: "goblin",
    shape: "circle",
    label: "哥布林",
    maxHp: 90,
    def: 0,
    atk: 12,
    range: 1,
    cd: 800,
    eva: 10,
    blk: 0,
  },
  HARPY: {
    enemyType: "harpy",
    shape: "triangle-down",
    label: "哈比鷹身人",
    maxHp: 130,
    def: 1,
    atk: 18,
    range: 1,
    cd: 600,
    eva: 20,
    blk: 0,
  },
  DIRE_WOLF: {
    enemyType: "direwolf",
    shape: "diamond",
    label: "兇暴狼獸",
    maxHp: 95,
    def: 0,
    atk: 22,
    range: 1,
    cd: 500,
    eva: 15,
    blk: 0,
  },
  ORC: {
    enemyType: "orc",
    shape: "square",
    label: "獸人戰士",
    maxHp: 260,
    def: 3,
    atk: 25,
    range: 1,
    cd: 1000,
    eva: 2,
    blk: 10,
  },
  SUCCUBUS: {
    enemyType: "succubus",
    shape: "circle",
    label: "魅魔",
    maxHp: 380,
    def: 2,
    atk: 35,
    range: 3,
    cd: 1100,
    eva: 12,
    blk: 0,
  },
  GARGOYLE: {
    enemyType: "gargoyle",
    shape: "square",
    label: "石像鬼",
    maxHp: 550,
    def: 10,
    atk: 40,
    range: 1,
    cd: 1200,
    eva: 0,
    blk: 20,
  },
  TROLL: {
    enemyType: "troll",
    shape: "triangle-up",
    label: "巨魔",
    maxHp: 800,
    def: 4,
    atk: 50,
    range: 1,
    cd: 1300,
    eva: 5,
    blk: 5,
  },

  // --- 🔮 精英怪物軍團 (關卡中隨機亂入的強敵) ---
  SKELETON_TYRANT: {
    enemyType: "orc",
    shape: "triangle-up",
    label: "骷髏暴君",
    maxHp: 1100, // 🩸 大砍 400 血量
    def: 6,
    atk: 55, // ⚔️ 攻擊力 90 ➡️ 55（拒絕一刀秒殺）
    range: 1,
    cd: 1100, // ⏱️ 攻速 700ms ➡️ 1100ms（變為笨重慢速重擊怪，可被高格擋克制）
    eva: 5,
    blk: 20,
    isElite: true,
    // 💡 概念技能：【不屈亡骨】防禦雖高，但動作極慢，可用高頻率輸出的刺客或破甲單位快速拆解
  },

  NECRO_ASSASSIN: {
    enemyType: "direwolf",
    shape: "diamond",
    label: "死靈刺客",
    maxHp: 550, // 🩸 血量 800 ➡️ 550（極致脆皮，只要抓到就能一發秒殺）
    def: 0, // 防禦歸零
    atk: 45, // ⚔️ 攻擊力 140 ➡️ 45（修正畸形秒傷）
    range: 1,
    cd: 600, // ⏱️ 攻速 400ms ➡️ 600ms（回歸刺客正常高頻範疇）
    eva: 25, // 閃避微調，保留刺客特色
    blk: 0,
    isElite: true,
    // 💡 概念技能：【致命偷襲】高攻速脆皮，只要在前排擺放「坦克」拉住仇恨，後排遠程就能一發把它點爆
  },

  TROLL_PRIEST: {
    enemyType: "troll",
    shape: "cross",
    label: "巨魔祭司",
    maxHp: 1200, // 🩸 血量 1800 ➡️ 1200（終於打得穿了）
    def: 2,
    atk: 35, // ⚔️ 攻擊力 50 ➡️ 35
    range: 2,
    cd: 1400, // ⏱️ 施法冷卻變長
    eva: 5,
    blk: 5,
    isElite: true,
    // 💡 概念技能：【巨魔圖騰】攻低血厚，主要威脅是中排輔助，可以用遊俠或法師等遠程射程壓制直接點殺
  },

  STORM_WITCH: {
    enemyType: "succubus",
    shape: "circle",
    label: "風暴魔女",
    maxHp: 750, // 🩸 血量 1100 ➡️ 750
    def: 1,
    atk: 50, // ⚔️ 攻擊力 110 ➡️ 50（傷害攔腰斬斷，防止後排全屏蒸發）
    range: 4,
    cd: 1200, // ⏱️ 施法 CD 1000ms ➡️ 1200ms
    eva: 10,
    blk: 0,
    isElite: true,
    // 💡 概念技能：【風暴詠唱】高威脅遠程，但極度怕突進。只要陣線沒崩，玩家有轉職出的「魔弓手」或「遊俠」，射程直接對點回擊
  },

  // --- 🩸 關卡首領級 (大關卡 Boss) ---
  IRON_GOLEM: {
    enemyType: "gargoyle",
    shape: "square",
    label: "鋼鐵傀儡·毀滅者",
    maxHp: 12000,
    def: 25,
    atk: 250,
    range: 1,
    cd: 1800,
    eva: 0,
    blk: 30,
    isBoss: true,
  },
  LUCIFER: {
    enemyType: "succubus",
    shape: "cross",
    label: "墮落大天使·路西法",
    maxHp: 8500,
    def: 12,
    atk: 320,
    range: 3,
    cd: 800,
    eva: 25,
    blk: 15,
    isBoss: true,
  },

  // --- 🌌 終極災難王級 (Raid Boss 決戰支配者) ---
  KRAKEN: {
    enemyType: "kraken",
    shape: "diamond",
    label: "虛空吞噬者·卡薩丁",
    maxHp: 18000, // 🩸 基礎血量 35000 ➡️ 18000
    def: 12, // 🛡️ 防禦 20 ➡️ 12
    atk: 180, // ⚔️ 攻擊 450 ➡️ 180（拒絕一刀秒殺前排）
    range: 2,
    cd: 1000,
    eva: 0,
    blk: 15,
    isBoss: true,
    isRaidBoss: true,
  },
  BALROG: {
    enemyType: "balrog",
    shape: "triangle-up",
    label: "煉獄炎魔·巴洛格",
    maxHp: 20000, // 🩸 基礎血量 38000 ➡️ 20000
    def: 10,
    atk: 220, // ⚔️ 攻擊 500 ➡️ 220（手短近戰，給予相對應的高單發傷害）
    range: 1,
    cd: 1200, // ⏱️ CD 1100ms ➡️ 1200ms（稍微放慢揮刀速度）
    eva: 5,
    blk: 15,
    isBoss: true,
    isRaidBoss: true,
  },
  DRAGON_KING: {
    enemyType: "dragon_king",
    shape: "square",
    label: "滅世巨龍·奧杜因",
    maxHp: 24000, // 🩸 基礎血量 45000 ➡️ 24000（放大後最終實戰約 5 萬血）
    def: 18, // 🛡️ 防禦 30 ➡️ 18（讓後排弓箭手不至於打出抓癢數字）
    atk: 160, // ⚔️ 攻擊 400 ➡️ 160（因為牠射程有 3 格，屬於遠程群轟，傷害必須壓低）
    range: 3,
    cd: 1400, // ⏱️ CD 1200ms ➡️ 1400ms（巨龍吐息需要更長的準備時間）
    eva: 0,
    blk: 20,
    isBoss: true,
    isRaidBoss: true,
  },
};

export const FACTIONS = { PLAYER: "blue", ENEMY: "red" };
export const GRID_ROWS = 5;
export const GRID_COLS = 5;

export const createUnitInstance = (blueprint, faction, customId = null) => {
  // 🎯 鋼鐵防線：如果奇遇事件或存檔丟進來的藍圖是 undefined，自動用基礎戰士頂替，絕不報錯崩潰
  const bp = blueprint || {
    shape: "square",
    label: "戰士",
    maxHp: 600,
    def: 2,
    atk: 55,
    range: 1,
    cd: 800,
    eva: 0,
    blk: 0,
    canPromote: true,
    price: 15,
  };

  return {
    id: customId || `${faction}-${bp.shape}-${Date.now()}-${Math.random()}`,
    shape: bp.shape,
    label: bp.label,
    maxHp: bp.maxHp,
    hp: bp.maxHp,
    def: bp.def,
    atk: bp.atk,
    range: bp.range,
    cd: bp.cd,
    eva: bp.eva !== undefined ? bp.eva : 0,
    blk: bp.blk !== undefined ? bp.blk : 0,
    faction: faction,
    nextActionTime: 0,
    visualState: "idle",
    skillCount: 0,
    isStealth: false,
    proClass: null,
    canPromote: bp.canPromote !== false,
    price: bp.price || 0,
    // 補上後續合成管線需要的血統標籤
    isPlus: bp.isPlus || false,
    isAdvanced: bp.isAdvanced || false,
    isLegendary: bp.isLegendary || false,
  };
};
